apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: netology
spec:
  environments:
    stage:
      defaultNamespace: qbec-stage
      server: https://10.10.80.13:6443
    prod:
      defaultNamespace: qbec-prod
      server: https://10.10.80.13:6443
      includes:
        - endpoint
  vars: {}
  excludes:
    - endpoint
